// LOCAL FILES
// Icons & Images
import { villagerIcon } from "assets/villager";
// Interfaces & Types
import type { Villager } from "features/villager/types";

export const ID_TO_VILLAGER: Record<number, Villager> = {
  1: {
    id: 1,
    name: "Tom",
    occupation: "Wizard",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  2: {
    id: 2,
    name: "Kobus",
    occupation: "Gargoyle",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  3: {
    id: 3,
    name: "Neil",
    occupation: "Arcane Architect",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  4: {
    id: 4,
    name: "Spirit",
    occupation: "Thoughtsmith",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  5: {
    id: 5,
    name: "Alex",
    occupation: "Moderator",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  6: {
    id: 6,
    name: "Angie",
    occupation: "Bard",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  7: {
    id: 7,
    name: "Malivil",
    occupation: "Maladin",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  8: {
    id: 8,
    name: "Technofrood",
    occupation: "Machinator",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  9: {
    id: 9,
    name: "Jason",
    occupation: "Smallholder",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  10: {
    id: 10,
    name: "Alistair",
    occupation: "Chorister",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  11: {
    id: 11,
    name: "Alex",
    occupation: "Swede",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  12: {
    id: 12,
    name: "Bruce",
    occupation: "Siege Engineer",
    description: "Dildo merchant and sex pest.",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  13: {
    id: 13,
    name: "Dan",
    occupation: "Forester",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  14: {
    id: 14,
    name: "Jordy",
    occupation: "Trickster",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  15: {
    id: 15,
    name: "Putzly",
    occupation: "Miner",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  16: {
    id: 16,
    name: "Shorts",
    occupation: "GIFsmith",
    description: "Makes GIFs, fucks grannies. Refuses to elaborate.",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  17: {
    id: 17,
    name: "Spaaz",
    occupation: "Baker",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  18: {
    id: 18,
    name: "Umbra",
    occupation: "Gemcarver",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  19: {
    id: 19,
    name: "Vodrix",
    occupation: "Blacksmith",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  20: {
    id: 20,
    name: "Vilidoug",
    occupation: "Metalurgist",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  21: {
    id: 21,
    name: "Woodysus",
    occupation: "Joiner",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  22: {
    id: 22,
    name: "Zoarino",
    occupation: "Archeologist",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  23: {
    id: 23,
    name: "Placeholder_1",
    occupation: "Carpenter",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  24: {
    id: 24,
    name: "Placeholder_2",
    occupation: "Carver",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  25: {
    id: 25,
    name: "Aartvark",
    occupation: "Painter",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  26: {
    id: 26,
    name: "Dapper",
    occupation: "Lightsmith",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  27: {
    id: 27,
    name: "Whitesage",
    occupation: "Chef",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  28: {
    id: 28,
    name: "Ash",
    occupation: "Whitesmith",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  29: {
    id: 29,
    name: "Brady",
    occupation: "Feller",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  30: {
    id: 30,
    name: "Dingy",
    occupation: "Ranger",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  31: {
    id: 31,
    name: "Ellen",
    occupation: "Bowyer",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  32: {
    id: 32,
    name: "Jaakko",
    occupation: "Fool & Court Jester",
    description:
      "A man too fucking drunk to be of any use to the town. He may come out with a wise word every now and then though.",
    canRecruit: false,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: -1,
      Stone: -1,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  33: {
    id: 33,
    name: "Gianni",
    occupation: "Hunter",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  34: {
    id: 34,
    name: "Jar",
    occupation: "Alchemist",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  35: {
    id: 35,
    name: "Crimmy",
    occupation: "Warrior",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  36: {
    id: 36,
    name: "Lexie",
    occupation: "Artist",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  37: {
    id: 37,
    name: "Lou",
    occupation: "Librarian",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  38: {
    id: 38,
    name: "Ricardo",
    occupation: "Armourer",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  39: {
    id: 39,
    name: "Siggy",
    occupation: "Hooper",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  40: {
    id: 40,
    name: "Sky",
    occupation: "Roofer",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  41: {
    id: 41,
    name: "Bulba",
    occupation: "Trainer",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  42: {
    id: 42,
    name: "Sean",
    occupation: "Translator",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  43: {
    id: 43,
    name: "Tensa",
    occupation: "Builder",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  44: {
    id: 44,
    name: "Stig",
    occupation: "LUAnist",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  45: {
    id: 45,
    name: "Tiger",
    occupation: "Rancher",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
  46: {
    id: 46,
    name: "TJ",
    occupation: "Sea Captain",
    description: "",
    canRecruit: true,
    requirements: {
      tier: 1,
      buildingIds: [],
      villagerIds: [],
    },
    gatherResources: {
      Wood: 0,
      Stone: 0,
      Iron: 0,
      Steel: 0,
      Mythril: 0,
      Amethyst: 0,
    },
    militaryStrength: {
      handToHand: 1,
      archery: 1,
      mounted: 1,
    },
    icons: {
      healthy: villagerIcon,
      recovering: villagerIcon,
      injured: villagerIcon,
      dead: villagerIcon,
    },
  },
};
