// LOCAL FILES
// Constants
import { NO_RESOURCES } from "features/resource/constants";
// Icons & Images
import {
  buildingBeingRepairedIcon,
  buildingBuiltIcon,
  buildingDamagedIcon,
  buildingDestroyedIcon,
  buildingUnderConstructionIcon,
} from "assets/building";
// Interfaces & Types
import type {
  Building,
  BuildingRequirements,
} from "features/building/types";
// Utility functions
import { getBuildingRequirements } from "features/building/utils";
import { getResources } from "features/resource/utils";

export const NO_BUILDING_REQUIREMENTS: BuildingRequirements = {
  tier: 1,
  buildingIds: [],
  villagerIds: [],
};

export const BUILDING_ID_CARTROGRAPHER = 36;
export const BUILDING_ID_MARKET_STALL = 42;

/** Reference object for all buildings in the game */
export const ID_TO_BUILDING: Record<number, Building> = {
  1: {
    id: 1,
    name: "Small Cottages",
    text: {
      preBuild:
        "New faces are joining the village almost every day now. It's time people had a proper place to live! A row of small cottages can be put together quickly if we all work together.",
      postBuild:
        "A few days of labour and you stand before small, but cosy and warm cottages. Much better than the tents and shelters people were using! People are sure to work harder with a good roof over their heads.",
    },
    canBuild: true,
    requirements: NO_BUILDING_REQUIREMENTS,
    gatherResources: getResources({ Wood: 1 }),
    buildResources: getResources({ Wood: -50, Stone: -50 }),
    buildTime: 14,
    repairResources: getResources({ Wood: -25, Stone: -25 }),
    repairTime: 7,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  2: {
    id: 2,
    name: "Houses",
    text: {
      preBuild:
        "Well! A few weeks of planning and storing up some spare resources has flown by and now you can proudly welcome families from those cramped cottages and offer them a house worth being proud off.",
      postBuild:
        "They seem overjoyed and plans for decorating quickly overtake the conversations at dinner!",
    },
    canBuild: true,
    requirements: getBuildingRequirements({
      tier: 2,
      buildingIds: [1],
    }),
    gatherResources: getResources({ Wood: 1, Stone: 1 }),
    buildResources: getResources({ Wood: -100, Stone: -130 }),
    buildTime: 26,
    repairResources: getResources({ Wood: -50, Stone: -75 }),
    repairTime: 15,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  3: {
    id: 3,
    name: "Manor House",
    text: {
      preBuild:
        "Providing for the people of the town worked extremely well in terms of housing. The only problem is you also need a suitable home! A few stern words with a passing foreman and plans are quickly arranged.",
      postBuild:
        "A matter of days and a swarm of helpful and grateful townspeople are putting together the finishing touches on your new Manor, as befits your station. Lovely!",
    },
    canBuild: true,
    requirements: getBuildingRequirements({
      tier: 3,
      buildingIds: [2],
    }),
    gatherResources: getResources({ Wood: -1, Stone: -1, Iron: 1 }),
    buildResources: getResources({
      Wood: -300,
      Stone: -300,
      Iron: -100,
      Steel: -50,
    }),
    buildTime: 40,
    repairResources: getResources({
      Wood: -150,
      Stone: -150,
      Iron: -50,
      Steel: -25,
    }),
    repairTime: 20,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  4: {
    id: 4,
    name: "Knight's Motte & Bailey",
    text: {
      preBuild:
        "If war is to come to the valley and your siblings are to be brought to heel then we must be able to defend ourselves.",
      postBuild:
        "A true motte and bailey is quickly erected on your orders, rising over the highest hill in the town and displaying to all your martial might!",
    },
    canBuild: true,
    requirements: getBuildingRequirements({
      tier: 4,
      buildingIds: [3],
    }),
    gatherResources: getResources({ Stone: -1, Iron: -1, Steel: 1 }),
    buildResources: getResources({
      Wood: -500,
      Stone: -500,
      Iron: -300,
      Steel: -200,
    }),
    buildTime: 50,
    repairResources: getResources({
      Wood: -250,
      Stone: -250,
      Iron: -150,
      Steel: -100,
    }),
    repairTime: 25,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  5: {
    id: 5,
    name: "Priest's House",
    text: {
      preBuild:
        "With a priest safely ensconced in the town, they'll require somewhere to live which is a little more than a town house or cottage. After all, can't allow the mouthpiece of the gods to wash their laundry with the towns people! With a wry smile you commission the builders of the town to put together an appropriate dwelling for the priest, including a generous library of religious texts!",
      postBuild:
        "The priest is as excited as a child on midwinter's eve when you show them around the building!",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 2 }),
    gatherResources: getResources({ Wood: -1, Stone: 1 }),
    buildResources: getResources({
      Wood: -70,
      Stone: -70,
    }),
    buildTime: 30,
    repairResources: getResources({
      Wood: -35,
      Stone: -35,
    }),
    repairTime: 15,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  6: {
    id: 6,
    name: "Chapel",
    text: {
      preBuild:
        "The people seem to be lacking something. Their hands are busy but their hearts seem no longer in it. You rack your brains for days before realising that the people need greater purpose, more structure, as well as daily drudgery. You rush to the house of the Priest and have them put together plans for a modest chapel.",
      postBuild:
        "It isn't long before you are inspecting the newly completed building. Wonderful work, this should help give your people purpose!",
    },
    canBuild: true,
    requirements: getBuildingRequirements({
      tier: 3,
      buildingIds: [5],
    }),
    gatherResources: getResources({ Wood: -1, Stone: 1, Iron: 1 }),
    buildResources: getResources({
      Wood: -150,
      Stone: -150,
      Iron: -100,
    }),
    buildTime: 60,
    repairResources: getResources({
      Wood: -75,
      Stone: -75,
      Iron: -50,
    }),
    repairTime: 30,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  7: {
    id: 7,
    name: "Church",
    text: {
      preBuild:
        "Mass each week seems more and more full. People are standing in the aisles and children scurry underfoot between the pews, blatantly ignoring the fine work of our priest. This won't stand, we need more than a simple chapel for a town of our size. It's time to consecrate a decent church to venerate the gods.",
      postBuild:
        "Several months later, you preside over the opening ceremony - laying the final brick in the doorway of the new church. What better occassion than the opening of a new church to hold a fete? The people will surely be better able to deliver their work for the town now that they can be sure their souls will be saved and the gods will smile upon them!",
    },
    canBuild: true,
    requirements: getBuildingRequirements({
      tier: 4,
      buildingIds: [6],
    }),
    gatherResources: getResources({
      Wood: -1,
      Stone: 1,
      Iron: 1,
      Steel: 1,
    }),
    buildResources: getResources({
      Wood: -250,
      Stone: -250,
      Iron: -150,
      Steel: -100,
    }),
    buildTime: 90,
    repairResources: getResources({
      Wood: -125,
      Stone: -125,
      Iron: -75,
      Steel: -50,
    }),
    repairTime: 45,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  8: {
    id: 8,
    name: "Monastery",
    text: {
      preBuild:
        "Mass is ever more popular among the growing townsfolk, and now with so many children still too young to work and too young to sit through classes we need a guiding hand in the village around the services at the church. One of our oldest priests has put forth an idea, both as a place for priests to slow down their lives and as a useful place for the children to be kept while their parent's work. A monastery built in the grounds of our fine Church would not only serve both purposes but also be a lovely place to brew beer! Let's do it!",
      postBuild:
        "It was a lot of hard work for our builders. Hundreds of blocks of stone were quarried and rolled through town in order to construct the huge monastery that now sits proudly alongside our church. The swelling faith of our populace is something to be proud of!",
    },
    canBuild: true,
    requirements: getBuildingRequirements({
      tier: 5,
      buildingIds: [6],
    }),
    gatherResources: getResources({
      Wood: -1,
      Stone: -1,
      Iron: 1,
      Steel: 1,
      Mythril: 1,
    }),
    buildResources: getResources({
      Wood: -300,
      Stone: -300,
      Iron: -200,
      Steel: -200,
      Mythril: -100,
    }),
    buildTime: 130,
    repairResources: getResources({
      Wood: -150,
      Stone: -150,
      Iron: -100,
      Steel: -100,
      Mythril: -50,
    }),
    repairTime: 65,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  9: {
    id: 9,
    name: "Temple",
    text: {
      preBuild:
        "One fine morning a petitioner stands at your office doorway. 'Monarch, it's a fine church we have, and the priest tries to honour as many gods as possible, but to be honest with you we need a place that can be more than a church. A place for offerings, healing the sick, and for the priests to be able to minister more actively to the people. Like the temples in the old cities!'. That's not a bad idea, if we have a chance of combat, our priests more actively ministering to the sick could be very useful. A temple it is!",
      postBuild:
        "The first of the sick and feeble petitioners climbs the steps to the temple, into the waiting healing hands of the priests. It's a beautiful sight, seeing your people taken care of in this fashion, knowing that ailments will be cured and the blind will see again through the power of the gods. Probably shouldn't have put so many steps up to the doors though. We'll add a ramp next week.",
    },
    canBuild: true,
    requirements: getBuildingRequirements({
      tier: 5,
      buildingIds: [7],
    }),
    gatherResources: getResources({ Steel: 1, Amethyst: 1 }),
    buildResources: getResources({
      Wood: -350,
      Stone: -350,
      Iron: -250,
      Steel: -200,
      Mythril: -100,
    }),
    buildTime: 150,
    repairResources: getResources({
      Wood: -250,
      Stone: -250,
      Iron: -150,
      Steel: -100,
      Mythril: -50,
    }),
    repairTime: 75,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  10: {
    id: 10,
    name: "Graveyard",
    text: {
      preBuild:
        "It is an inevitable part of our lives. The bonfires outside of the city cannot keep up with the funerals, and some of our gloried dead shouldn't return to the earth so soon. Some must be preserved and remembered in stone, to allow our town the time it needs to grieve and hope that heroes will rise again. A graveyard where rememberance can be properly honoured would suit, certainly.",
      postBuild:
        "It was a huge undertaking. The ground had to be cleared, the headstones carved, the walls built, gates of iron and spells of peace cast around the hallowed ground to stop the dead rising. But at long last it is finally done, and our temple quarter is complete. Hope rises among the people, that although some may be lost, they will be remembered and honoured for time immemorial.",
    },
    canBuild: true,
    requirements: getBuildingRequirements({
      tier: 5,
      buildingIds: [9],
    }),
    gatherResources: getResources({ Iron: 1, Mythril: 1 }),
    buildResources: getResources({
      Wood: -400,
      Stone: -400,
      Iron: -200,
      Steel: -200,
      Mythril: -100,
    }),
    buildTime: 200,
    repairResources: getResources({
      Wood: -200,
      Stone: -200,
      Iron: -100,
      Steel: -100,
      Mythril: -50,
    }),
    repairTime: 100,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  11: {
    id: 11,
    name: "Grain Field",
    text: {
      preBuild:
        "The sun beats down as you inspect the area outlined by rough stakes. Surely this will be enough land, our people need vittles and our small vegetable patches are not filling bellies any longer. These few hectares will grow sufficient grain to keep our nascent town full of bread and beer for several seasons at least, giving us a foothold we sorely need in this valley.",
      postBuild:
        "Several long afternoons in the sun and the ground is turned, rocks have been removed and the land stands surrounded by a simple but effective stone wall. It's time for planting!",
    },
    canBuild: true,
    requirements: NO_BUILDING_REQUIREMENTS,
    gatherResources: getResources({ Wood: 1, Stone: 1 }),
    buildResources: getResources({
      Wood: -35,
      Stone: -100,
    }),
    buildTime: 10,
    repairResources: getResources({
      Wood: -15,
      Stone: -50,
    }),
    repairTime: 5,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  12: {
    id: 12,
    name: "Mill",
    text: {
      preBuild:
        "Food is becoming an issue in the town. Enough is grown but the speed of processing leaves much to be desired, and leaves much rotting in the fields! If you could make the food last longer it would be much easier to steady the food supply. Nothing for it but to order a Mill built so we can properly process the crops.",
      postBuild:
        "No more than a week later you hear the creak and crack of the great sails of the Mill turning for the first time in the wind. Excellent! On to the next crisis!",
    },
    canBuild: true,
    requirements: getBuildingRequirements({
      tier: 2,
      buildingIds: [11],
    }),
    gatherResources: getResources({ Wood: 1, Stone: 1, Iron: 1 }),
    buildResources: getResources({
      Wood: -150,
      Stone: -250,
      Iron: -35,
    }),
    buildTime: 20,
    repairResources: getResources({
      Wood: -75,
      Stone: -125,
      Iron: -15,
    }),
    repairTime: 10,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  13: {
    id: 13,
    name: "Bakery",
    text: {
      preBuild:
        "Walking home after a day of gathering resources you are led by your nose down a path you normally would not take. A scintilating smell pulls you along until you stop at a pie and a loaf of spiced bread cooling on a window sill. You are just about to take a bite of fruit pie when a firm smack with a rolling pin brings you to your senses. 'You listen here, king or not, you ask when you want a slice of my pie! If you want I'd be happy to make you your own, I'll make as many as the town needs but manners cost nothing!' Utterly ashamed and now utterly starving you rush to order a bakery put together for this fine woman so she can supply her treats to the whole town.",
      postBuild:
        "Days later you stand before a new bakery, eagerly awaiting your first pie!",
    },
    canBuild: true,
    requirements: getBuildingRequirements({
      tier: 2,
      buildingIds: [12],
    }),
    gatherResources: getResources({ Wood: 1, Stone: 1 }),
    buildResources: getResources({
      Wood: -60,
      Stone: -40,
    }),
    buildTime: 8,
    repairResources: getResources({
      Wood: -30,
      Stone: -20,
    }),
    repairTime: 4,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  14: {
    id: 14,
    name: "Granary",
    text: {
      preBuild:
        "The bakery you ordered built has kept the people happy and pudgy, especially you and your quickly growing waist! Clearly though, it's not enough - this morning there was no bread or pie! The baker said that although we have plenty of grain in the fields and the Mill is working overtime, moving so much grain around the town is becoming an issue. We need a central granary to simplify it and allow grain to all who need it.",
      postBuild:
        "The new granary rises over the rooftops surrounding it and shines brightly in the morning sun. Beautiful, well organised and full of delicious grain ready to be turned into even more delicious cakes and pies! Wonderful!",
    },
    canBuild: true,
    requirements: getBuildingRequirements({
      tier: 3,
      buildingIds: [13],
    }),
    gatherResources: getResources({ Iron: 1 }),
    buildResources: getResources({
      Wood: -100,
      Stone: -80,
      Iron: -20,
    }),
    buildTime: 16,
    repairResources: getResources({
      Wood: -50,
      Stone: -40,
      Iron: -10,
    }),
    repairTime: 8,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  15: {
    id: 15,
    name: "Town Square",
    text: {
      preBuild:
        "As a fifteenth person tries to squeeze into your little office for a meeting, the rest shuffling and sneezing, you lose patience with this. \"Right! We're building up the town square, it's time for a proper meeting place where we can address the whole village at once! No other business until that ground is flattened, paved and ready for a stage!\"",
      postBuild:
        "It's only a short time later that you stand atop the stage and look out over the several hundred people who now call this town home. How quickly it's all happened! Stepping over to the centre of the stage you call, \"My good people! I happily declare this town square open and ready for use! Now, the first order of business...\"",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 2 }),
    gatherResources: getResources({ Stone: 1 }),
    buildResources: getResources({ Wood: -20, Stone: -90 }),
    buildTime: 10,
    repairResources: getResources({ Wood: -10, Stone: -45 }),
    repairTime: 5,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  16: {
    id: 16,
    name: "Town Hall",
    text: {
      preBuild:
        'The muttering of the ground grows louder and you can barely hear what is being said by your council on stage in the town square. "Quiet!", you roar for the tenth time. Damn it, how loud three hundred whispers can be. You stand, forestalling the next comment from your council. "We must have a Town Hall. To register the births and deaths of this fine town, and as a place for the business of the town to be conducted in good order". You stride off, already shouting at nearby builders.',
      postBuild:
        "Ah, the smell of a ceremonial ribbon. Nothing like it. With a deft flick of your scissors, you declare the new town hall open and ready for business. The waiting crowd seems more bemused than happy, but they clap politely nonetheless.",
    },
    canBuild: true,
    requirements: getBuildingRequirements({
      tier: 4,
      buildingIds: [15],
    }),
    gatherResources: getResources({ Iron: 1 }),
    buildResources: getResources({
      Wood: -100,
      Stone: -100,
      Iron: -100,
      Steel: -100,
    }),
    buildTime: 40,
    repairResources: getResources({
      Wood: -50,
      Stone: -50,
      Iron: -50,
      Steel: -50,
    }),
    repairTime: 20,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  17: {
    id: 17,
    name: "Mint",
    text: {
      preBuild:
        "Opening the window to your office in the town hall, you are immediately assaulted by the roar of trade in the marketplace nearby. Not a bad roar, to hear so much active trade but it doesn't half give you a headache. Listening carefully, most of the shouting seems to be people setting terms and arguing over what they will trade in. We should standardise and introduce a proper coinage, not only is it good for our nacsent nation but it's good for your ears!",
      postBuild:
        "The mint is finally done. It's a quiet building full of artisans of metal carefully printing, stamping and chipping away at precious gold to make fine coins bearing your royal visage.",
    },
    canBuild: true,
    requirements: getBuildingRequirements({
      tier: 5,
      buildingIds: [16],
    }),
    gatherResources: getResources({ Steel: 1 }),
    buildResources: getResources({
      Wood: -200,
      Stone: -200,
      Iron: -200,
      Steel: -200,
    }),
    buildTime: 80,
    repairResources: getResources({
      Wood: -100,
      Stone: -100,
      Iron: -100,
      Steel: -100,
    }),
    repairTime: 40,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  18: {
    id: 18,
    name: "Bank",
    text: {
      preBuild:
        "A heavy clink rips you from your train of thought. Another bag of gold landing on the table. It's good that the people have taken so enthusiastically to your currency, but the sheer weight of some purses has people employing others simply to carry their wealth around! We need a place to store all of this gold, a central bank. With the smile of a shark you order for the builders to attend. You've got a plan...",
      postBuild:
        "A sunny day shines down as barrow after barrow of glistening coin is wheeled carefully into the newly finished bank. The money lenders are setting up shop nearby and the economy of the town is sure to ramp up now.",
    },
    canBuild: true,
    requirements: getBuildingRequirements({
      tier: 5,
      buildingIds: [17],
    }),
    gatherResources: getResources({
      Iron: 1,
      Steel: 1,
      Mythril: 1,
      Amethyst: 1,
    }),
    buildResources: getResources({
      Wood: -400,
      Stone: -400,
      Iron: -400,
      Steel: -400,
      Mythril: -400,
    }),
    buildTime: 100,
    repairResources: getResources({
      Wood: -200,
      Stone: -200,
      Iron: -200,
      Steel: -200,
      Mythril: -200,
    }),
    repairTime: 50,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  19: {
    id: 19,
    name: "Blacksmith",
    text: {
      preBuild: "",
      postBuild:
        "Proudly, you stand back in the cart track and look up at the new smithy. It's a fine building and will help produce excellent tools to gather the resources hidden in this lush valley.",
    },
    canBuild: false,
    requirements: NO_BUILDING_REQUIREMENTS,
    gatherResources: getResources({ Wood: 1, Stone: 1 }),
    buildResources: getResources({ Wood: -80, Stone: -90 }),
    buildTime: 25,
    repairResources: getResources({ Wood: -40, Stone: -45 }),
    repairTime: 15,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  20: {
    id: 20,
    name: "Charcoal Maker",
    text: {
      preBuild:
        "A bang on the door rouses you from a peaceful slumber by the fire. Groggily you answer and are accosted by the smith! 'M'lord, it's no bloody good! We need better fuel if we're to keep up production - we're just going through too much wood!' Before a response can rise to your lips the smith is gone, returned to the wind and the night as quickly as they arrived.",
      postBuild:
        "Right-o, then! I've seen smoke over the trees near the far fields, tomorrow a guard is being sent to recruit those bloody charcoal makers and have them send their goods to town. Maybe then people around here will be able to sleep in peace!",
    },
    canBuild: true,
    requirements: getBuildingRequirements({
      tier: 2,
      buildingIds: [19],
    }),
    gatherResources: getResources({ Wood: 1 }),
    buildResources: getResources({
      Wood: -50,
      Stone: -20,
      Iron: -5,
    }),
    buildTime: 5,
    repairResources: getResources({
      Wood: -25,
      Stone: -10,
      Iron: -3,
    }),
    repairTime: 2,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  21: {
    id: 21,
    name: "Woodcutter",
    text: {
      preBuild:
        "The smell of fresh pine sap and drying racks of wood fills the air. With a smile and a huge noseful of the pleasant scent you check on the work of the Woodcutter. ",
      postBuild:
        "Quickly realising much more has been done than you thought you are presented with a large and industrious wood cutting shop - full of the tools and space needed to efficiently increase production in your burgeoning town!",
    },
    canBuild: true,
    requirements: NO_BUILDING_REQUIREMENTS,
    gatherResources: getResources({ Wood: 1 }),
    buildResources: getResources({ Wood: -100, Stone: -100 }),
    buildTime: 10,
    repairResources: getResources({ Wood: -50, Stone: -50 }),
    repairTime: 5,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  22: {
    id: 22,
    name: "Sawmill",
    text: {
      preBuild:
        "Walking down the street you are stopped in your tracks by pallet after pallet of raw wood and felled trees blocking your way. What is the meaning of this? Curiously you enter the nearby woodcutter's and ask what has happened. \"We can't keep up!\" comes the hasty reply before the apprentice scurries off to process another tree. Hmm, this won't do. Perhaps a full sawmill outside of the town will be better?",
      postBuild:
        "A veritable forest of industry surrounds you as you stand amid the roaring of sawblades, processing felled trees deftly and quickly. And importantly, not doing so inside the town any longer!",
    },
    canBuild: true,
    requirements: getBuildingRequirements({
      tier: 3,
      buildingIds: [21],
    }),
    gatherResources: getResources({ Wood: 5 }),
    buildResources: getResources({
      Wood: -300,
      Stone: -100,
      Iron: -50,
    }),
    buildTime: 50,
    repairResources: getResources({
      Wood: -150,
      Stone: -50,
      Iron: -25,
    }),
    repairTime: 25,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  23: {
    id: 23,
    name: "Fishery",
    text: {
      preBuild:
        "Gods! What a day in the village! The sun is high in the sky, and the waters are crystal clear in the river. Abundance surrounds you, and you notice for the first time that the number of fat slow fish in the river has increased steadily in your time here. Thoughts of fried fish on your mind you have a word with one of the lads nearby and send them running to fetch the builders. A proper fishery will help us take advantage of the blessings the gods of water have sent. And think of all the delicious fish!",
      postBuild:
        "Belly full and mouth greasy, you look at the crowd surrounding the new fishery. Happy, smiling faces everywhere you look! Another success!",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 2 }),
    gatherResources: getResources({ Wood: 1, Stone: 1, Iron: 1 }),
    buildResources: getResources({
      Wood: -100,
      Stone: -50,
      Iron: -50,
    }),
    buildTime: 13,
    repairResources: getResources({
      Wood: -50,
      Stone: -25,
      Iron: -25,
    }),
    repairTime: 7,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  24: {
    id: 24,
    name: "Brewery",
    text: {
      preBuild:
        "Small-scale brewing has been keeping the village watered for some time now, but a growing complaint among the people is the lack of variety and quantitiy of beverage. You have to agree, beer after beer is very repetitive, especially after a hard day at the quarry or the iron mine! You call for a builder and ask what it would take to put together a proper brewery. With a shy smile, the brewer informs you that work has already begun! Monarchs may command everything around them it seems, as long as the beer flows freely.",
      postBuild:
        "Before you know it the brewery is rolling out the first barrels of beer, cider, wine and schnapps. A very merry opening day was had by all, and the free alcohol did not hurt proceedings!",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 3 }),
    gatherResources: getResources({ Wood: 1, Stone: 1, Iron: 1 }),
    buildResources: getResources({
      Wood: -200,
      Stone: -200,
      Iron: -200,
    }),
    buildTime: 50,
    repairResources: getResources({
      Wood: -100,
      Stone: -100,
      Iron: -100,
    }),
    repairTime: 25,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  25: {
    id: 25,
    name: "Mason",
    text: {
      preBuild:
        "The freshly trod dirt roads outlining the beating thoroughfares of your town are extremely cluttered. What you assumed to be gravel paths turns out to simply be chips and offcuts from the quarrymen! Two stubbed toes and a curse later you march into the stone yard and order a proper masons be built forthwith! ",
      postBuild:
        "The masons have been hard at work and, eager not to rouse your anger again, have carved themselves a fantastic workshop made of fine stone. They quickly and happily point out to you the deep offcut pits they have built for all of the spoilt bits of rock. Excellent.",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 3 }),
    gatherResources: getResources({ Wood: -1, Stone: 10 }),
    buildResources: getResources({ Wood: -100, Stone: -500 }),
    buildTime: 50,
    repairResources: getResources({ Wood: -50, Stone: -250 }),
    repairTime: 25,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  26: {
    id: 26,
    name: "Orchard",
    text: {
      preBuild:
        "The village lacks the vibrant abundance of fruit trees, leaving its residents longing for the taste of nature's sweet harvest. An orchard, with its bountiful array of apple, pear, and cherry trees, would bring color to the landscape and provide a vital source of nourishment. It would be a sanctuary where families gather, children play, and the fragrance of blossoms intermingles with the whispers of a community's dreams.",
      postBuild:
        "Within the village, a newfound sense of vibrancy and abundance fills the air. The once barren landscape has transformed into a flourishing orchard, bursting with life and color. Lush apple, pear, and cherry trees stand tall, their branches heavy with ripe fruits. The village now enjoys a bounty of nourishment and sustenance, bringing joy to the faces of its residents. Families gather beneath the shade of the trees, sharing laughter and stories as they savor the sweetness of nature's gifts. The orchard has become the heart of the community, a sanctuary of serenity and prosperity that uplifts the spirits of all who dwell within its embrace.",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 3 }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  27: {
    id: 27,
    name: "Barn",
    text: {
      preBuild:
        "In the heart of the village, a collective yearning for a shelter for their precious livestock and harvested crops echoes through the air. With each passing day, the need for a sturdy barn grows more evident. The village lacks a central space to store their provisions, protect their animals, and gather during inclement weather. The desire for a barn becomes a shared dream, where animals find refuge, bountiful harvests are preserved, and community bonds are strengthened. With the construction of a barn, the village would gain a symbol of resilience and unity, providing the foundation for their sustenance and prosperity.",
      postBuild:
        "Within the village, a sense of fulfillment and security emanates from the recently constructed barn. Its sturdy beams and thatched roof stand as a testament to the hard work and collective effort of the villagers. The barn is now a bustling hub of activity, with livestock finding shelter within its protective walls and bales of harvested crops neatly stored. Villagers gather within its warm confines, sharing stories and enjoying the fruits of their labor. The barn has become the heart of the community, providing a tangible symbol of abundance and resilience, ensuring a prosperous future for all who call the village home.",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 2 }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  28: {
    id: 28,
    name: "Tavern",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 3 }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  29: {
    id: 29,
    name: "Pasture",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 4 }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  30: {
    id: 30,
    name: "Alchemist",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 3 }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  31: {
    id: 31,
    name: "Armoury",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 4 }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  32: {
    id: 32,
    name: "Aviary",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 3 }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  33: {
    id: 33,
    name: "Barracks",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 4 }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  34: {
    id: 34,
    name: "Boathouse",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 3 }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  35: {
    id: 35,
    name: "Carpenter",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: NO_BUILDING_REQUIREMENTS,
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  [BUILDING_ID_CARTROGRAPHER]: {
    id: BUILDING_ID_CARTROGRAPHER,
    name: "Cartographer",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 3 }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  37: {
    id: 37,
    name: "Tailor",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 2 }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  38: {
    id: 38,
    name: "Council Chamber",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 4 }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  39: {
    id: 39,
    name: "Fletcher",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 3 }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  40: {
    id: 40,
    name: "Guildhall",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 4 }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  41: {
    id: 41,
    name: "Infirmary",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 4 }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  [BUILDING_ID_MARKET_STALL]: {
    id: BUILDING_ID_MARKET_STALL,
    name: "Market Stall",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 2 }),
    gatherResources: NO_RESOURCES,
    buildResources: getResources({ Wood: -10, Stone: -10 }),
    buildTime: 6,
    repairResources: getResources({ Wood: -5, Stone: -5 }),
    repairTime: 3,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  43: {
    id: 43,
    name: "Stables",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 3 }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  44: {
    id: 44,
    name: "Stonemason",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: NO_BUILDING_REQUIREMENTS,
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  45: {
    id: 45,
    name: "Warehouse",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 2 }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  46: {
    id: 46,
    name: "Well",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: NO_BUILDING_REQUIREMENTS,
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  47: {
    id: 47,
    name: "Wizard Tower",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: false,
    requirements: getBuildingRequirements({
      tier: 5,
      villagerIds: [1],
    }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 10,
    repairResources: NO_RESOURCES,
    repairTime: 10,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  48: {
    id: 48,
    name: "Gatehouse",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: getBuildingRequirements({ tier: 3 }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  49: {
    id: 49,
    name: "City Walls",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: getBuildingRequirements({
      tier: 4,
      buildingIds: [48],
    }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
  50: {
    id: 50,
    name: "Alarm Beacon",
    text: {
      preBuild: "",
      postBuild: "",
    },
    canBuild: true,
    requirements: getBuildingRequirements({
      tier: 4,
      buildingIds: [49],
    }),
    gatherResources: NO_RESOURCES,
    buildResources: NO_RESOURCES,
    buildTime: 1,
    repairResources: NO_RESOURCES,
    repairTime: 1,
    icons: {
      built: buildingBuiltIcon,
      "under construction": buildingUnderConstructionIcon,
      "being repaired": buildingBeingRepairedIcon,
      damaged: buildingDamagedIcon,
      destroyed: buildingDestroyedIcon,
    },
  },
};
