export const BUTTON_HEIGHT = 45;
export const DEFAULT_NINE_SLICE_BORDER_WIDTH = 8;
export const DEFAULT_NINE_SLICE_BUTTON_HORIZONTAL_BORDER_WIDTH = 4;
export const DEFAULT_NINE_SLICE_BUTTON_VERTICAL_BORDER_WIDTH = 4;
export const TABLE_ROW_HEIGHT = 40;
