// LOCAL FILES
// Constants
import { NO_RESOURCES } from "features/resource/constants";
// Interfaces & Types
import type { MapTile } from "features/map/types";

export const MAP_TILES: MapTile[] = [
  {
    x: 0,
    y: 0,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 1,
    y: 0,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 2,
    y: 0,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 3,
    y: 0,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 4,
    y: 0,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 5,
    y: 0,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 6,
    y: 0,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 7,
    y: 0,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 8,
    y: 0,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 9,
    y: 0,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 0,
    y: 1,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 1,
    y: 1,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 2,
    y: 1,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 3,
    y: 1,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 4,
    y: 1,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 5,
    y: 1,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 6,
    y: 1,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 7,
    y: 1,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 8,
    y: 1,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 9,
    y: 1,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 0,
    y: 2,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 1,
    y: 2,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 2,
    y: 2,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 3,
    y: 2,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 4,
    y: 2,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 5,
    y: 2,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 6,
    y: 2,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 7,
    y: 2,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 8,
    y: 2,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 9,
    y: 2,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 0,
    y: 3,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 1,
    y: 3,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 2,
    y: 3,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 3,
    y: 3,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 4,
    y: 3,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 5,
    y: 3,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 6,
    y: 3,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 7,
    y: 3,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 8,
    y: 3,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 9,
    y: 3,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 0,
    y: 4,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 1,
    y: 4,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 2,
    y: 4,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 3,
    y: 4,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 4,
    y: 4,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 5,
    y: 4,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 6,
    y: 4,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 7,
    y: 4,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 8,
    y: 4,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 9,
    y: 4,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 0,
    y: 5,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 1,
    y: 5,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 2,
    y: 5,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 3,
    y: 5,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 4,
    y: 5,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 5,
    y: 5,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 6,
    y: 5,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 7,
    y: 5,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 8,
    y: 5,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 9,
    y: 5,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 0,
    y: 6,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 1,
    y: 6,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 2,
    y: 6,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 3,
    y: 6,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 4,
    y: 6,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 5,
    y: 6,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 6,
    y: 6,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 7,
    y: 6,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 8,
    y: 6,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 9,
    y: 6,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 0,
    y: 7,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 1,
    y: 7,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 2,
    y: 7,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 3,
    y: 7,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 4,
    y: 7,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 5,
    y: 7,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 6,
    y: 7,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 7,
    y: 7,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 8,
    y: 7,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 9,
    y: 7,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 0,
    y: 8,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 1,
    y: 8,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 2,
    y: 8,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 3,
    y: 8,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 4,
    y: 8,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 5,
    y: 8,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 6,
    y: 8,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 7,
    y: 8,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 8,
    y: 8,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 9,
    y: 8,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 0,
    y: 9,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 1,
    y: 9,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 2,
    y: 9,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 3,
    y: 9,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 4,
    y: 9,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 5,
    y: 9,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 6,
    y: 9,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 7,
    y: 9,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 8,
    y: 9,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
  {
    x: 9,
    y: 9,
    eventId: null,
    spyAmount: 0,
    visible: false,
    explored: false,
    resources: NO_RESOURCES,
    isTown: false,
    isPlayerTown: false,
  },
];
