// LOCAL FILES
// Interfaces & Types
import type { Tile } from "features/map/types";

export const TILES: Tile[] = [
  {
    x: 0,
    y: 0,
    eventId: null,
    scoutAmount: 3,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 1,
    y: 0,
    eventId: null,
    scoutAmount: 2,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 2,
    y: 0,
    eventId: null,
    scoutAmount: 1,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 0,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 0,
    eventId: null,
    scoutAmount: 0,
    visible: true,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 5,
    y: 0,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 6,
    y: 0,
    eventId: null,
    scoutAmount: 1,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 0,
    eventId: null,
    scoutAmount: 2,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 8,
    y: 0,
    eventId: null,
    scoutAmount: 3,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 9,
    y: 0,
    eventId: null,
    scoutAmount: 4,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 0,
    y: 1,
    eventId: null,
    scoutAmount: 3,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 1,
    y: 1,
    eventId: null,
    scoutAmount: 2,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 2,
    y: 1,
    eventId: null,
    scoutAmount: 1,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 1,
    eventId: null,
    scoutAmount: 0,
    visible: true,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 1,
    eventId: null,
    scoutAmount: 0,
    visible: true,
    explored: true,
    resources: null,
    playerId: 1,
  },
  {
    x: 5,
    y: 1,
    eventId: null,
    scoutAmount: 0,
    visible: true,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 6,
    y: 1,
    eventId: null,
    scoutAmount: 1,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 1,
    eventId: null,
    scoutAmount: 2,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 8,
    y: 1,
    eventId: null,
    scoutAmount: 3,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 9,
    y: 1,
    eventId: null,
    scoutAmount: 4,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 0,
    y: 2,
    eventId: null,
    scoutAmount: 3,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 1,
    y: 2,
    eventId: null,
    scoutAmount: 2,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 2,
    y: 2,
    eventId: null,
    scoutAmount: 1,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 2,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 2,
    eventId: null,
    scoutAmount: 0,
    visible: true,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 5,
    y: 2,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 6,
    y: 2,
    eventId: null,
    scoutAmount: 1,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 2,
    eventId: null,
    scoutAmount: 2,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 8,
    y: 2,
    eventId: null,
    scoutAmount: 3,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 9,
    y: 2,
    eventId: null,
    scoutAmount: 4,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 0,
    y: 3,
    eventId: null,
    scoutAmount: 3,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 1,
    y: 3,
    eventId: null,
    scoutAmount: 2,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 2,
    y: 3,
    eventId: null,
    scoutAmount: 1,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 3,
    eventId: null,
    scoutAmount: 1,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 3,
    eventId: null,
    scoutAmount: 1,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 5,
    y: 3,
    eventId: null,
    scoutAmount: 1,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 6,
    y: 3,
    eventId: null,
    scoutAmount: 1,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 3,
    eventId: null,
    scoutAmount: 2,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 8,
    y: 3,
    eventId: null,
    scoutAmount: 3,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 9,
    y: 3,
    eventId: null,
    scoutAmount: 4,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 0,
    y: 4,
    eventId: null,
    scoutAmount: 3,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 1,
    y: 4,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: 2,
  },
  {
    x: 2,
    y: 4,
    eventId: null,
    scoutAmount: 2,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 4,
    eventId: null,
    scoutAmount: 2,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 4,
    eventId: null,
    scoutAmount: 2,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 5,
    y: 4,
    eventId: null,
    scoutAmount: 2,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 6,
    y: 4,
    eventId: null,
    scoutAmount: 2,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 4,
    eventId: null,
    scoutAmount: 2,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 8,
    y: 4,
    eventId: null,
    scoutAmount: 3,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 9,
    y: 4,
    eventId: null,
    scoutAmount: 4,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 0,
    y: 5,
    eventId: null,
    scoutAmount: 3,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 1,
    y: 5,
    eventId: null,
    scoutAmount: 3,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 2,
    y: 5,
    eventId: null,
    scoutAmount: 3,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 5,
    eventId: null,
    scoutAmount: 3,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 5,
    eventId: null,
    scoutAmount: 3,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 5,
    y: 5,
    eventId: null,
    scoutAmount: 3,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 6,
    y: 5,
    eventId: null,
    scoutAmount: 3,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 5,
    eventId: null,
    scoutAmount: 3,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 8,
    y: 5,
    eventId: null,
    scoutAmount: 3,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 9,
    y: 5,
    eventId: null,
    scoutAmount: 4,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 0,
    y: 6,
    eventId: null,
    scoutAmount: 4,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 1,
    y: 6,
    eventId: null,
    scoutAmount: 4,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 2,
    y: 6,
    eventId: null,
    scoutAmount: 4,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 6,
    eventId: null,
    scoutAmount: 4,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 6,
    eventId: null,
    scoutAmount: 4,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 5,
    y: 6,
    eventId: null,
    scoutAmount: 4,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 6,
    y: 6,
    eventId: null,
    scoutAmount: 4,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 6,
    eventId: null,
    scoutAmount: 4,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 8,
    y: 6,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: 3,
  },
  {
    x: 9,
    y: 6,
    eventId: null,
    scoutAmount: 4,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 0,
    y: 7,
    eventId: null,
    scoutAmount: 5,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 1,
    y: 7,
    eventId: null,
    scoutAmount: 5,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 2,
    y: 7,
    eventId: null,
    scoutAmount: 5,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 7,
    eventId: null,
    scoutAmount: 5,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 7,
    eventId: null,
    scoutAmount: 5,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 5,
    y: 7,
    eventId: null,
    scoutAmount: 5,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 6,
    y: 7,
    eventId: null,
    scoutAmount: 5,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 7,
    eventId: null,
    scoutAmount: 5,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 8,
    y: 7,
    eventId: null,
    scoutAmount: 5,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 9,
    y: 7,
    eventId: null,
    scoutAmount: 5,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 0,
    y: 8,
    eventId: null,
    scoutAmount: 6,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 1,
    y: 8,
    eventId: null,
    scoutAmount: 6,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 2,
    y: 8,
    eventId: null,
    scoutAmount: 6,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 8,
    eventId: null,
    scoutAmount: 6,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 8,
    eventId: null,
    scoutAmount: 6,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 5,
    y: 8,
    eventId: null,
    scoutAmount: 6,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 6,
    y: 8,
    eventId: null,
    scoutAmount: 6,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 8,
    eventId: null,
    scoutAmount: 6,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 8,
    y: 8,
    eventId: null,
    scoutAmount: 6,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 9,
    y: 8,
    eventId: null,
    scoutAmount: 6,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 0,
    y: 9,
    eventId: null,
    scoutAmount: 7,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 1,
    y: 9,
    eventId: null,
    scoutAmount: 7,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 2,
    y: 9,
    eventId: null,
    scoutAmount: 7,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 9,
    eventId: null,
    scoutAmount: 7,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 9,
    eventId: null,
    scoutAmount: 7,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 5,
    y: 9,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: 4,
  },
  {
    x: 6,
    y: 9,
    eventId: null,
    scoutAmount: 7,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 9,
    eventId: null,
    scoutAmount: 7,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 8,
    y: 9,
    eventId: null,
    scoutAmount: 7,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 9,
    y: 9,
    eventId: null,
    scoutAmount: 7,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
];
