// LOCAL FILES
// Assets
import {
  mapTilex1y1Image,
  mapTilex2y1Image,
  mapTilex3y1Image,
  mapTilex4y1Image,
  mapTilex5y1Image,
  mapTilex6y1Image,
  mapTilex7y1Image,
  mapTilex8y1Image,
  mapTilex9y1Image,
  mapTilex10y1Image,
  mapTilex1y2Image,
  mapTilex2y2Image,
  mapTilex3y2Image,
  mapTilex4y2Image,
  mapTilex5y2Image,
  mapTilex6y2Image,
  mapTilex7y2Image,
  mapTilex8y2Image,
  mapTilex9y2Image,
  mapTilex10y2Image,
  mapTilex1y3Image,
  mapTilex2y3Image,
  mapTilex3y3Image,
  mapTilex4y3Image,
  mapTilex5y3Image,
  mapTilex6y3Image,
  mapTilex7y3Image,
  mapTilex8y3Image,
  mapTilex9y3Image,
  mapTilex10y3Image,
  mapTilex1y4Image,
  mapTilex2y4Image,
  mapTilex3y4Image,
  mapTilex4y4Image,
  mapTilex5y4Image,
  mapTilex6y4Image,
  mapTilex7y4Image,
  mapTilex8y4Image,
  mapTilex9y4Image,
  mapTilex10y4Image,
  mapTilex1y5Image,
  mapTilex2y5Image,
  mapTilex3y5Image,
  mapTilex4y5Image,
  mapTilex5y5Image,
  mapTilex6y5Image,
  mapTilex7y5Image,
  mapTilex8y5Image,
  mapTilex9y5Image,
  mapTilex10y5Image,
  mapTilex1y6Image,
  mapTilex2y6Image,
  mapTilex3y6Image,
  mapTilex4y6Image,
  mapTilex5y6Image,
  mapTilex6y6Image,
  mapTilex7y6Image,
  mapTilex8y6Image,
  mapTilex9y6Image,
  mapTilex10y6Image,
  mapTilex1y7Image,
  mapTilex2y7Image,
  mapTilex3y7Image,
  mapTilex4y7Image,
  mapTilex5y7Image,
  mapTilex6y7Image,
  mapTilex7y7Image,
  mapTilex8y7Image,
  mapTilex9y7Image,
  mapTilex10y7Image,
  mapTilex1y8Image,
  mapTilex2y8Image,
  mapTilex3y8Image,
  mapTilex4y8Image,
  mapTilex5y8Image,
  mapTilex6y8Image,
  mapTilex7y8Image,
  mapTilex8y8Image,
  mapTilex9y8Image,
  mapTilex10y8Image,
  mapTilex1y9Image,
  mapTilex2y9Image,
  mapTilex3y9Image,
  mapTilex4y9Image,
  mapTilex5y9Image,
  mapTilex6y9Image,
  mapTilex7y9Image,
  mapTilex8y9Image,
  mapTilex9y9Image,
  mapTilex10y9Image,
  mapTilex1y10Image,
  mapTilex2y10Image,
  mapTilex3y10Image,
  mapTilex4y10Image,
  mapTilex5y10Image,
  mapTilex6y10Image,
  mapTilex7y10Image,
  mapTilex8y10Image,
  mapTilex9y10Image,
  mapTilex10y10Image,
} from "assets/map";
// Interfaces & Types
import type { Tile } from "features/map/types";

export const MAP_TILE_WIDTH = 102;

export const TILES: Tile[] = [
  {
    x: 1,
    y: 1,
    image: mapTilex1y1Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 2,
    y: 1,
    image: mapTilex2y1Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 1,
    image: mapTilex3y1Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 1,
    image: mapTilex4y1Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 5,
    y: 1,
    image: mapTilex5y1Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 6,
    y: 1,
    image: mapTilex6y1Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 1,
    image: mapTilex7y1Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 8,
    y: 1,
    image: mapTilex8y1Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 9,
    y: 1,
    image: mapTilex9y1Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 10,
    y: 1,
    image: mapTilex10y1Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 1,
    y: 2,
    image: mapTilex1y2Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 2,
    y: 2,
    image: mapTilex2y2Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 2,
    image: mapTilex3y2Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 2,
    image: mapTilex4y2Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 5,
    y: 2,
    image: mapTilex5y2Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 6,
    y: 2,
    image: mapTilex6y2Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 2,
    image: mapTilex7y2Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 8,
    y: 2,
    image: mapTilex8y2Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 9,
    y: 2,
    image: mapTilex9y2Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 10,
    y: 2,
    image: mapTilex10y2Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 1,
    y: 3,
    image: mapTilex1y3Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 2,
    y: 3,
    image: mapTilex2y3Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 3,
    image: mapTilex3y3Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 3,
    image: mapTilex4y3Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 5,
    y: 3,
    image: mapTilex5y3Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 6,
    y: 3,
    image: mapTilex6y3Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 3,
    image: mapTilex7y3Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 8,
    y: 3,
    image: mapTilex8y3Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 9,
    y: 3,
    image: mapTilex9y3Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 10,
    y: 3,
    image: mapTilex10y3Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 1,
    y: 4,
    image: mapTilex1y4Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 2,
    y: 4,
    image: mapTilex2y4Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 4,
    image: mapTilex3y4Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 4,
    image: mapTilex4y4Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 5,
    y: 4,
    image: mapTilex5y4Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 6,
    y: 4,
    image: mapTilex6y4Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 4,
    image: mapTilex7y4Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 8,
    y: 4,
    image: mapTilex8y4Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 9,
    y: 4,
    image: mapTilex9y4Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 10,
    y: 4,
    image: mapTilex10y4Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 1,
    y: 5,
    image: mapTilex1y5Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 2,
    y: 5,
    image: mapTilex2y5Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 5,
    image: mapTilex3y5Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 5,
    image: mapTilex4y5Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 5,
    y: 5,
    image: mapTilex5y5Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 6,
    y: 5,
    image: mapTilex6y5Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 5,
    image: mapTilex7y5Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 8,
    y: 5,
    image: mapTilex8y5Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 9,
    y: 5,
    image: mapTilex9y5Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 10,
    y: 5,
    image: mapTilex10y5Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 1,
    y: 6,
    image: mapTilex1y6Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 2,
    y: 6,
    image: mapTilex2y6Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 6,
    image: mapTilex3y6Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 6,
    image: mapTilex4y6Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 5,
    y: 6,
    image: mapTilex5y6Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 6,
    y: 6,
    image: mapTilex6y6Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 6,
    image: mapTilex7y6Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 8,
    y: 6,
    image: mapTilex8y6Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 9,
    y: 6,
    image: mapTilex9y6Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 10,
    y: 6,
    image: mapTilex10y6Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 1,
    y: 7,
    image: mapTilex1y7Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 2,
    y: 7,
    image: mapTilex2y7Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 7,
    image: mapTilex3y7Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 7,
    image: mapTilex4y7Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 5,
    y: 7,
    image: mapTilex5y7Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 6,
    y: 7,
    image: mapTilex6y7Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 7,
    image: mapTilex7y7Image,
    eventId: null,
    scoutAmount: 0,
    visible: true,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 8,
    y: 7,
    image: mapTilex8y7Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 9,
    y: 7,
    image: mapTilex9y7Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 10,
    y: 7,
    image: mapTilex10y7Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 1,
    y: 8,
    image: mapTilex1y8Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 2,
    y: 8,
    image: mapTilex2y8Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 8,
    image: mapTilex3y8Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 8,
    image: mapTilex4y8Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 5,
    y: 8,
    image: mapTilex5y8Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 6,
    y: 8,
    image: mapTilex6y8Image,
    eventId: null,
    scoutAmount: 0,
    visible: true,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 8,
    image: mapTilex7y8Image,
    eventId: null,
    scoutAmount: 0,
    visible: true,
    explored: true,
    resources: null,
    playerId: 1,
  },
  {
    x: 8,
    y: 8,
    image: mapTilex8y8Image,
    eventId: null,
    scoutAmount: 0,
    visible: true,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 9,
    y: 8,
    image: mapTilex9y8Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 10,
    y: 8,
    image: mapTilex10y8Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 1,
    y: 9,
    image: mapTilex1y9Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 2,
    y: 9,
    image: mapTilex2y9Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 9,
    image: mapTilex3y9Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 9,
    image: mapTilex4y9Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 5,
    y: 9,
    image: mapTilex5y9Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 6,
    y: 9,
    image: mapTilex6y9Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 9,
    image: mapTilex7y9Image,
    eventId: null,
    scoutAmount: 0,
    visible: true,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 8,
    y: 9,
    image: mapTilex8y9Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 9,
    y: 9,
    image: mapTilex9y9Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 10,
    y: 9,
    image: mapTilex10y9Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 1,
    y: 10,
    image: mapTilex1y10Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 2,
    y: 10,
    image: mapTilex2y10Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 3,
    y: 10,
    image: mapTilex3y10Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 4,
    y: 10,
    image: mapTilex4y10Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 5,
    y: 10,
    image: mapTilex5y10Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 6,
    y: 10,
    image: mapTilex6y10Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 7,
    y: 10,
    image: mapTilex7y10Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 8,
    y: 10,
    image: mapTilex8y10Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 9,
    y: 10,
    image: mapTilex9y10Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
  {
    x: 10,
    y: 10,
    image: mapTilex10y10Image,
    eventId: null,
    scoutAmount: 0,
    visible: false,
    explored: false,
    resources: null,
    playerId: null,
  },
];
